HairSalon/Models/Client.cs
namespace HairSalon.Models
{
  public class Client
  {
  public int ClientId { get; set; }
  public string Name { get; set; }
  public int StylistId { get; set; }
  public string Notes { get; set; }
  }
}

HairSalon/Controllers/ClientController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using HairSalon.Models;
using System.Linq;
using System.Collections.Generic;

namespace HairSalon.Controllers
{
  public class ClientController : Controller
  {
    private readonly SalonContext _db;
    public ClientController(SalonContext db)
    {
      _db = db;
    }
    public ActionResult Index()
    {
      List<Client> clients = _db.Clients.ToList();
      Dictionary<int,string> stylistNames = new Dictionary<int,string>();
      foreach (Stylist stylist in _db.Stylists.ToList())
      {
        stylistNames.Add(stylist.StylistId,stylist.Name);
      }

      ViewBag.Stylists = stylistNames;
      return View(clients);
    }
    public ActionResult Create()
    {
      List<SelectListItem> items = new SelectList(_db.Stylists, "StylistId","Name").ToList();
      items.Insert(0, (new SelectListItem { Text = "No Stylist", Value = "0" }));
      ViewBag.StylistId = items;
      return View();
    }
    [HttpPost]
    public ActionResult Create(Client client)
    {
      _db.Clients.Add(client);
      if (client.StylistId != 0)
      {
        Stylist entry = _db.Stylists.FirstOrDefault(stylist => stylist.StylistId == client.StylistId);
        entry.CustomerCount += 1;
        _db.Entry(entry).State = EntityState.Modified;
      }
      _db.SaveChanges();
      return RedirectToAction("Index","Client");
    }
    public ActionResult Delete(int id)
    {
      return View(_db.Clients.FirstOrDefault(client => client.ClientId == id));
    }
    
    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Client client = _db.Clients.FirstOrDefault(client => client.ClientId == id);
      if (client.StylistId != 0)
      {
        Stylist changedStylist = _db.Stylists.FirstOrDefault(stylist => stylist.StylistId == client.StylistId);
        changedStylist.CustomerCount -= 1;
        _db.Entry(changedStylist).State = EntityState.Modified;
      }
      _db.Clients.Remove(client);
      _db.SaveChanges();
      return  RedirectToAction("Index");
    }
    public ActionResult Edit(int id)
    {
      // Dictionary<int,string> stylistNames = new Dictionary<int,string>();
      // foreach (Stylist stylist in _db.Stylists.ToList())
      // {
      //   stylistNames.Add(stylist.StylistId,stylist.Name);
      // }
      Client client = _db.Clients.FirstOrDefault(client => client.ClientId == id);
      if (client.StylistId != 0)
      {
        Stylist changedStylist = _db.Stylists.FirstOrDefault(stylist => stylist.StylistId == client.StylistId);
        changedStylist.CustomerCount -= 1;
        _db.Entry(changedStylist).State = EntityState.Modified;
        _db.SaveChanges();
      }
      List<SelectListItem> items = new SelectList(_db.Stylists, "StylistId","Name").ToList();
      items.Insert(0, (new SelectListItem { Text = "No Stylist", Value = "0" }));
      ViewBag.Stylists = items;
      return View(client);
    }
    [HttpPost]
    public ActionResult Edit(Client client)
    {
      if (client.StylistId != 0)
      {
        Stylist changedStylist = _db.Stylists.FirstOrDefault(stylist => stylist.StylistId == client.StylistId);
        changedStylist.CustomerCount += 1;
        _db.Entry(changedStylist).State = EntityState.Modified;
        _db.SaveChanges();
      }
      _db.Entry(client).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

HairSalon/Controllers/ClientsController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using HairSalon.Models;
using System.Linq;
using System.Collections.Generic;

namespace HairSalon.Controllers
{
  public class ClientsController : Controller
  {
    private readonly SalonContext _db;
    public ClientsController(SalonContext db)
    {
      _db = db;
    }
    public ActionResult Index()
    {
      List<Client> clients = _db.Clients.ToList();
      Dictionary<int,string> stylistNames = new Dictionary<int,string>();
      foreach (Stylist stylist in _db.Stylists.ToList())
      {
        stylistNames.Add(stylist.StylistId,stylist.Name);
      }

      ViewBag.Stylists = stylistNames;
      return View(clients);
    }
    public ActionResult Create()
    {
      List<SelectListItem> items = new SelectList(_db.Stylists, "StylistId","Name").ToList();
      items.Insert(0, (new SelectListItem { Text = "No Stylist", Value = "0" }));
      ViewBag.StylistId = items;
      return View();
    }
    [HttpPost]
    public ActionResult Create(Client client)
    {
      _db.Clients.Add(client);
      if (client.StylistId != 0)
      {
        Stylist entry = _db.Stylists.FirstOrDefault(stylist => stylist.StylistId == client.StylistId);
        entry.CustomerCount += 1;
        _db.Entry(entry).State = EntityState.Modified;
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult Delete(int id)
    {
      return View(_db.Clients.FirstOrDefault(client => client.ClientId == id));
    }
    
    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Client client = _db.Clients.FirstOrDefault(client => client.ClientId == id);
      if (client.StylistId != 0)
      {
        Stylist changedStylist = _db.Stylists.FirstOrDefault(stylist => stylist.StylistId == client.StylistId);
        changedStylist.CustomerCount -= 1;
        _db.Entry(changedStylist).State = EntityState.Modified;
      }
      _db.Clients.Remove(client);
      _db.SaveChanges();
      return  RedirectToAction("Index");
    }
    public ActionResult Edit(int id)
    {
      Client client = _db.Clients.FirstOrDefault(client => client.ClientId == id);
      if (client.StylistId != 0)
      {
        Stylist changedStylist = _db.Stylists.FirstOrDefault(stylist => stylist.StylistId == client.StylistId);
        changedStylist.CustomerCount -= 1;
        _db.Entry(changedStylist).State = EntityState.Modified;
        _db.SaveChanges();
      }
      List<SelectListItem> items = new SelectList(_db.Stylists, "StylistId","Name").ToList();
      items.Insert(0, (new SelectListItem { Text = "No Stylist", Value = "0" }));
      ViewBag.Stylists = items;
      return View(client);
    }
    [HttpPost]
    public ActionResult Edit(Client client)
    {
      if (client.StylistId != 0)
      {
        Stylist changedStylist = _db.Stylists.FirstOrDefault(stylist => stylist.StylistId == client.StylistId);
        changedStylist.CustomerCount += 1;
        _db.Entry(changedStylist).State = EntityState.Modified;
        _db.SaveChanges();
      }
      _db.Entry(client).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

HairSalon/Views/Clients/Create.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Client;

<h1>Add Client</h1>
@using (Html.BeginForm())
{
  <div class="form-group">
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name, new { @class = "form-control", required="required"})
  </div>
  <div class="form-group">
  @Html.LabelFor(model => model.Notes)
  @Html.TextAreaFor(model => model.Notes, new { @class = "form-control" })
  </div>
  <div class="form-group">
  @Html.LabelFor(model => model.StylistId, "Stylist")
  @Html.DropDownList("StylistId",ViewBag.StylistId,"Add Stylist",new { @class = "form-control", required="required"})
  </div>
  <input type="submit" value="Add Client" class="btn btn-success btn-center" />
}

HairSalon/Views/Clients/Delete.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Client
<button class="btn btn-info black">@Html.ActionLink("Cancel","Index", new {id = Model.ClientId})</button>
<h2>Are you sure you want to remove @Model.Name ?</h2>
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" class="btn btn-danger btn-center"/>
}

HairSalon/Views/Clients/Edit.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Client;

<h1>Add Client</h1>
@using (Html.BeginForm())
{
  <div class="form-group">
  @Html.HiddenFor(model => model.ClientId)
  </div>
  <div class="form-group">
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
  </div>
  <div class="form-group">
  @Html.LabelFor(model => model.Notes)
  @Html.TextAreaFor(model => model.Notes, new { @class = "form-control" })
  </div>
  <div class="form-group">
  @Html.LabelFor(model => model.StylistId, "Stylist")
  @Html.DropDownList("StylistId",ViewBag.Stylists,"Edit Stylist",new { @class = "form-control" })
  </div>
  <button class="btn btn-danger black btn-center">@Html.ActionLink("Cancel", "Index")</button>
  <input type="submit" value="Edit Client" class="btn btn-success btn-center" />
}

HairSalon/Views/Clients/Index.cshtml
@{
  Layout = "_Layout";
}
@using HairSalon.Models;


<h1>Clients</h1>
<div class="PageAction">
  <p class="btn btn-info black">@Html.ActionLink("Add New Client", "Create")</p>
</div>

<div class="TableContainer">
  <div class="container">
    @if (@Model.Count == 0)
    {
      <h3>No Clients currently registered</h3>
    }
    else
    {
      <div class="row TableHeader">
        <div class="col-1"></div>
        <div class="col">Name</div>
        <div class="col">Assigned Stylist</div>
        <div class="col-2">Delete</div>
      </div>
    }

    @foreach (Client client in Model)
    {
      <div class="row TableEntry">
      <div class="col-1">
        <p class="BlueBtn TableButton black BtnSpacer">@Html.ActionLink("Edit","Edit","Clients", new { id = client.ClientId})</p>
      </div>
      <div class="col">@client.Name</div>
      <div class="col">
        @if (client.StylistId != 0)
        {
          @ViewBag.Stylists[client.StylistId];
        }
        else
        {
          <p>Not Assigned</p>
        }
      </div>
      <div class="col-2"><p class = "TableButton RedBtn black BtnSpacer">@Html.ActionLink("Delete","Delete","Clients", new { id = client.ClientId})</p></div>
      </div>
    }
    <div class="row TableFooter"></div>
  </div>
</div>